config/routes.rb
Rails.application.routes.draw do
  resources :contracts

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'admin/dashboard#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contract.rb
class Contract < ActiveRecord::Base
	validates :account, presence: true, uniqueness: true
	validates :customer, presence: true
	validates :title, presence: true
	validates :contract_no, presence: true, uniqueness: true
	validates :status, inclusion: {in: %w(A C),
				message: "Status can be either A or C"}
	#validates :revenue_to_date, :funded_amount, absence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contracts_controller.rb
class ContractsController < InheritedResources::Base
	def new
		@contract = Contract.new
	end

	def index
		@contracts = Contract.all
	end

	def create
		@contract = Contract.create(accepted_params)
		#render plain: (accepted_params).inspect
		if @contract.save
			redirect_to :action => :index
		else
			render :action => :new
		end		
	end

	def show
		@contract = Contract.find(params[:id])
	end

private
  def accepted_params
    params.require(:contract).permit(:account, :customer, :title, :contract_no, :status, :start_date, :current_end_date, :end_date_w_options,
     :revenue_to_date, :funded_amount, :company, :div_pool, :operating_div, :basis, :vehicle, :contract_type, :ecs_role, :signed_contract_amount,
     :account_ex, :director, :project_manager, :cont_admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<%= form_for(@contract) do |f| %>
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account %><br>
    <%= f.text_field :account %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contract_no %><br>
    <%= f.text_field :contract_no %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :current_end_date %><br>
    <%= f.date_select :current_end_date %>
  </div>
  <div class="field">
    <%= f.label :end_date_w_options %><br>
    <%= f.date_select :end_date_w_options %>
  </div>
  <div class="field">
    <%= f.label :revenue_to_date %><br>
    <%= f.text_field :revenue_to_date %>
  </div>
  <div class="field">
    <%= f.label :funded_amount %><br>
    <%= f.text_field :funded_amount %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :div_pool %><br>
    <%= f.number_field :div_pool %>
  </div>
  <div class="field">
    <%= f.label :operating_div %><br>
    <%= f.text_field :operating_div %>
  </div>
  <div class="field">
    <%= f.label :basis %><br>
    <%= f.text_field :basis %>
  </div>
  <div class="field">
    <%= f.label :vehicle %><br>
    <%= f.text_field :vehicle %>
  </div>
  <div class="field">
    <%= f.label :contract_type %><br>
    <%= f.text_field :contract_type %>
  </div>
  <div class="field">
    <%= f.label :ecs_role %><br>
    <%= f.text_field :ecs_role %>
  </div>
  <div class="field">
    <%= f.label :signed_contract_amount %><br>
    <%= f.text_field :signed_contract_amount %>
  </div>
  <div class="field">
    <%= f.label :account_ex %><br>
    <%= f.text_field :account_ex %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :project_manager %><br>
    <%= f.text_field :project_manager %>
  </div>
  <div class="field">
    <%= f.label :cont_admin %><br>
    <%= f.text_field :cont_admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing contract</h1>

<%= render 'form' %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<h1>Listing contracts</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Customer</th>
      <th>Title</th>
      <th>Contract no</th>
      <th>Status</th>
      <th>Start date</th>
      <th>Current end date</th>
      <th>End date w options</th>
      <th>Revenue to date</th>
      <th>Funded amount</th>
      <th>Company</th>
      <th>Div pool</th>
      <th>Operating div</th>
      <th>Basis</th>
      <th>Vehicle</th>
      <th>Contract type</th>
      <th>Ecs role</th>
      <th>Signed contract amount</th>
      <th>Account ex</th>
      <th>Director</th>
      <th>Project manager</th>
      <th>Cont admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.account %></td>
        <td><%= contract.customer %></td>
        <td><%= contract.title %></td>
        <td><%= contract.contract_no %></td>
        <td><%= contract.status %></td>
        <td><%= contract.start_date %></td>
        <td><%= contract.current_end_date %></td>
        <td><%= contract.end_date_w_options %></td>
        <td><%= contract.revenue_to_date %></td>
        <td><%= contract.funded_amount %></td>
        <td><%= contract.company %></td>
        <td><%= contract.div_pool %></td>
        <td><%= contract.operating_div %></td>
        <td><%= contract.basis %></td>
        <td><%= contract.vehicle %></td>
        <td><%= contract.contract_type %></td>
        <td><%= contract.ecs_role %></td>
        <td><%= contract.signed_contract_amount %></td>
        <td><%= contract.account_ex %></td>
        <td><%= contract.director %></td>
        <td><%= contract.project_manager %></td>
        <td><%= contract.cont_admin %></td>
        <td><%= link_to 'Show', contract %></td>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<h1>New contract</h1>

<%= render 'form' %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @contract.account %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @contract.customer %>
</p>

<p>
  <strong>Title:</strong>
  <%= @contract.title %>
</p>

<p>
  <strong>Contract no:</strong>
  <%= @contract.contract_no %>
</p>

<p>
  <strong>Status:</strong>
  <%= @contract.status %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @contract.start_date %>
</p>

<p>
  <strong>Current end date:</strong>
  <%= @contract.current_end_date %>
</p>

<p>
  <strong>End date w options:</strong>
  <%= @contract.end_date_w_options %>
</p>

<p>
  <strong>Revenue to date:</strong>
  <%= @contract.revenue_to_date %>
</p>

<p>
  <strong>Funded amount:</strong>
  <%= @contract.funded_amount %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contract.company %>
</p>

<p>
  <strong>Div pool:</strong>
  <%= @contract.div_pool %>
</p>

<p>
  <strong>Operating div:</strong>
  <%= @contract.operating_div %>
</p>

<p>
  <strong>Basis:</strong>
  <%= @contract.basis %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @contract.vehicle %>
</p>

<p>
  <strong>Contract type:</strong>
  <%= @contract.contract_type %>
</p>

<p>
  <strong>Ecs role:</strong>
  <%= @contract.ecs_role %>
</p>

<p>
  <strong>Signed contract amount:</strong>
  <%= @contract.signed_contract_amount %>
</p>

<p>
  <strong>Account ex:</strong>
  <%= @contract.account_ex %>
</p>

<p>
  <strong>Director:</strong>
  <%= @contract.director %>
</p>

<p>
  <strong>Project manager:</strong>
  <%= @contract.project_manager %>
</p>

<p>
  <strong>Cont admin:</strong>
  <%= @contract.cont_admin %>
</p>

<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contractapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>